In [2]:
import Day

In [3]:
from Day import first,second

In [4]:
print(dir(first))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'factorial', 'is_even', 'is_odd']


In [5]:
print(dir(second))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'is_palindrome', 'string_methods']


In [6]:
help(first.factorial)

Help on function factorial in module Day.first:

factorial(n)
    # is_odd()



In [7]:
first.factorial(5)

factorial of  5 = 120


In [8]:
help(second.string_methods)

Help on function string_methods in module Day.second:

string_methods(st, ch)



In [9]:
second.string_methods("VVIT located at Nambur is an eng clg",'a')

frequency of  a = 4
startswith False
endswith  False
lowercase  vvit located at nambur is an eng clg
uppwercase  VVIT LOCATED AT NAMBUR IS AN ENG CLG
string to title  Vvit Located At Nambur Is An Eng Clg
sting to capitalize Vvit located at nambur is an eng clg


In [14]:
help(first_mod.factorial)

Help on function factorial in module package.first_mod:

factorial(n)
    #is_odd(n)



In [15]:
first_mod.factorial(5)

120

In [16]:
first_mod.is_even(4)

True

In [17]:
first_mod.is_even(5)

False

In [18]:
help(sec_mod.string_methods)

Help on function string_methods in module package.sec_mod:

string_methods(st, ch)
    # string methods



#### Introduction to Data Analysis
- information stored in a file
- kinds of data
    - Data in realtime
        1. Discrete
            - this type of data is fixed/constant
                - Ex:Nationality,Name,Color,aadhar number etc.
            - 2 types of data
                1. Qunatitative
                    - data is represented in terms of size/volume
                        - file size
                2. Qualitative 
                    - data is represented in the form of quality
                        - feedback form
        2. Continuous
            - height,weight etc
            
     - Data in our devices
         - images(.jpg,png,.jpeg)
         - videos(.mp4)
         - audio(.mp3)
         - exe
         
     - Data in Statistics
        1. Nominal
            - data is arranged based on the names
        2. Categorical
            - data is catogerized on the type
        3. Rational
            - data is in the form of p/q
        4. Interval
            - data stored in an interval/range
     

####  Modules
1. Numpy
    - one of the most important modules of data science
    - Numerical Python
    - mainly used for scientific computation of the data
2. Pandas
3. Matplotlib and seaborn

In [10]:
import numpy as n

In [11]:
n.__version__

'1.21.5'

In [13]:
print(dir(n))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

##### array()
- array() is the sub module of numpy
- array is the homogenous data structure allows the user to store only one type of data
- immutable in nature
- n.array(data)
- a user can create upto 32 dimensional array

In [14]:
help(n.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [15]:
print(n.array([4,5,6,10])) # array using list

[ 4  5  6 10]


In [16]:
print(n.array((5,6,7,90.45,'h')))

['5' '6' '7' '90.45' 'h']


In [17]:
print(n.array([4,9,45,23,90],dtype=float))

[ 4.  9. 45. 23. 90.]


In [18]:
print(n.array({'k':4,'v':5})) # 1 dimensional array

{'k': 4, 'v': 5}


In [19]:
#2d arrays : contains rows and columns
print(n.array([[1,2,3],[4,5,6]])) # [[],[]]

[[1 2 3]
 [4 5 6]]


In [20]:
ar=n.array([(1,2,3,4),(5,6,7,8),('a','b','c','d')])
ar

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['a', 'b', 'c', 'd']], dtype='<U11')

In [27]:
print(ar.dtype)
print(ar.size) # total no.of items in the array
print(ar.shape)
print(ar.ndim) # dimensions of the array

<U11
12
(3, 4)
2


##### arrays using some other functions
- arange()
- ones()
- zeros()
- full()
- fill()
- diag()
- identity()
- eye()
- linspace()
- random()

In [29]:
print(n.arange(100,125)) # 1d array
print(n.arange(100,125).reshape(5,5)) # 2d array
# 25:(1,25),(5,5),(25,1)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124]
[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]
 [120 121 122 123 124]]


In [34]:
ar=n.arange(100,500,30).reshape(2,7)
print(ar)

[[100 130 160 190 220 250 280]
 [310 340 370 400 430 460 490]]


In [40]:
print(n.arange(100,200,3).reshape(2,-3))

[[100 103 106 109 112 115 118 121 124 127 130 133 136 139 142 145 148]
 [151 154 157 160 163 166 169 172 175 178 181 184 187 190 193 196 199]]


In [42]:
print(n.arange(45).reshape(3,3,5)) # (n,r,c)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


In [45]:
# 32 dimensional array
print(n.array([4,5,6,10],ndmin=32,dtype=float))

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 4.  5.  6.
                                10.]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


In [52]:
print(n.ones(4))
print(n.ones((4,3)))

[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [53]:
print(n.zeros(5))
print(n.zeros((5,4)))

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [60]:
fl=n.full(4,'a')
fl2=n.full((4,5),9)
print(fl)
print(fl2)
fl2.fill(8)
fl2

['a' 'a' 'a' 'a']
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [61]:
n.diag([5,4,3,2,1])

array([[5, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

In [63]:
a=n.arange(25).reshape(-1,5)
print(a)
n.diag(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 0,  6, 12, 18, 24])

In [64]:
#linspace:linear space 
print(n.linspace(4,10))  # 50 partitions by default

[ 4.          4.12244898  4.24489796  4.36734694  4.48979592  4.6122449
  4.73469388  4.85714286  4.97959184  5.10204082  5.2244898   5.34693878
  5.46938776  5.59183673  5.71428571  5.83673469  5.95918367  6.08163265
  6.20408163  6.32653061  6.44897959  6.57142857  6.69387755  6.81632653
  6.93877551  7.06122449  7.18367347  7.30612245  7.42857143  7.55102041
  7.67346939  7.79591837  7.91836735  8.04081633  8.16326531  8.28571429
  8.40816327  8.53061224  8.65306122  8.7755102   8.89795918  9.02040816
  9.14285714  9.26530612  9.3877551   9.51020408  9.63265306  9.75510204
  9.87755102 10.        ]


In [65]:
#4,5,6,7,8,9,10:
7/50

0.14

In [67]:
print(n.linspace(4,10,16).reshape(4,4))

[[ 4.   4.4  4.8  5.2]
 [ 5.6  6.   6.4  6.8]
 [ 7.2  7.6  8.   8.4]
 [ 8.8  9.2  9.6 10. ]]


In [68]:
7/16

0.4375

#### random
- random is the sub module of numpy used to generate random data points
- n.random()
- n.random.random()
- n.random.rand()
- n.random.randn()
- n.random.randint()
- n.random.randint(,)
- n.random.randint(,,)

In [71]:
ar=n.random.random((3,4))
# it will generate random float values b/w 0&1
ar

array([[0.26536989, 0.23705877, 0.66713334, 0.12251019],
       [0.24200674, 0.94589305, 0.68583184, 0.03722562],
       [0.5851861 , 0.14582796, 0.17554906, 0.2341581 ]])

In [72]:
ar2=n.random.rand(3,4)
ar2

array([[0.73063879, 0.84749909, 0.37015054, 0.96295348],
       [0.38167859, 0.88821609, 0.96535359, 0.48382469],
       [0.68834705, 0.17588247, 0.40343111, 0.92755999]])

In [73]:
print(n.random.randn(3,3))

[[ 2.21425254e-02  8.10491834e-01 -4.22144153e-04]
 [-5.07581445e-01  1.37268152e+00  7.65112963e-01]
 [ 2.16995263e+00 -6.08146133e-01 -1.61167701e+00]]


In [77]:
print(dir(n.random))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'PCG64DXSM', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'tria