In [2]:
import numpy as np
import pandas as pd

In [4]:
ran=np.random.random((4,4)) # generates random float values
# b/w 0&1
ran

array([[0.5037409 , 0.07302136, 0.14783759, 0.3657999 ],
       [0.17549653, 0.56792542, 0.21268789, 0.83335587],
       [0.32244047, 0.93483715, 0.28519256, 0.38037685],
       [0.07179874, 0.55199336, 0.19177569, 0.7355894 ]])

In [5]:
print(np.random.rand(4,4))

[[0.36072914 0.52069391 0.97080343 0.65391695]
 [0.64844434 0.39895683 0.88264832 0.40447406]
 [0.53995151 0.07408912 0.62927807 0.89632881]
 [0.59100209 0.51979535 0.90993123 0.41517583]]


In [6]:
print(np.random.randn(4,4))

[[-1.69979669  0.28901979  1.31359974  0.53041271]
 [-0.03987778 -0.94260511 -0.08274462 -1.30477339]
 [ 0.34400209  0.69314106 -0.86265735 -0.45334211]
 [-0.61026661 -1.08297837 -1.64379068  0.67842303]]


In [13]:
# arithmetic operations on arrays
ar=np.random.randint(100,300,60) # st,stp,n
# 60:(1,60),(2,30),(3,20),(4,15),(5,12),(6,10) and vice-versa
# 60:(1,)
ar.reshape(2,3,10) # 60=2*3*10 # 3d array

array([[[168, 211, 250, 283, 281, 212, 292, 258, 122, 224],
        [128, 231, 202, 199, 163, 184, 172, 200, 288, 224],
        [131, 235, 120, 220, 227, 275, 123, 196, 118, 292]],

       [[133, 243, 160, 122, 271, 254, 129, 246, 212, 234],
        [125, 221, 123, 192, 295, 111, 187, 111, 104, 144],
        [256, 170, 153, 264, 103, 260, 241, 249, 155, 176]]])

In [14]:
print(np.arange(45).reshape(3,3,5))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]]


In [15]:
# create 2 equal size arrays and perform all the arithmetic operations
man=np.arange(25).reshape(5,5)
ran=np.random.randint(25,500,25).reshape(5,-1)
print(man)
print(ran)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[459 119 292 143  86]
 [ 27 294 257 411  91]
 [178 201 152  90 194]
 [236 459 270 266 189]
 [336  38 163 207 377]]


In [16]:
# all the arithmetic operations
print(ran+man)
print(ran-man)
print(man*ran)
print(ran/man)
print(ran%man)

[[459 120 294 146  90]
 [ 32 300 264 419 100]
 [188 212 164 103 208]
 [251 475 287 284 208]
 [356  59 185 230 401]]
[[459 118 290 140  82]
 [ 22 288 250 403  82]
 [168 190 140  77 180]
 [221 443 253 248 170]
 [316  17 141 184 353]]
[[   0  119  584  429  344]
 [ 135 1764 1799 3288  819]
 [1780 2211 1824 1170 2716]
 [3540 7344 4590 4788 3591]
 [6720  798 3586 4761 9048]]
[[         inf 119.         146.          47.66666667  21.5       ]
 [  5.4         49.          36.71428571  51.375       10.11111111]
 [ 17.8         18.27272727  12.66666667   6.92307692  13.85714286]
 [ 15.73333333  28.6875      15.88235294  14.77777778   9.94736842]
 [ 16.8          1.80952381   7.40909091   9.          15.70833333]]
[[ 0  0  0  2  2]
 [ 2  0  5  3  1]
 [ 8  3  8 12 12]
 [11 11 15 14 18]
 [16 17  9  0 17]]


C:\Users\ruthu\AppData\Local\Temp\ipykernel_24912\1115003698.py:5: RuntimeWarning: divide by zero encountered in true_divide
  print(ran/man)
C:\Users\ruthu\AppData\Local\Temp\ipykernel_24912\1115003698.py:6: RuntimeWarning: divide by zero encountered in remainder
  print(ran%man)


In [18]:
# scientific computations
# min,max,sum,mean,median,std
print(np.min(ran))
print(ran.min())
print(np.max(ran))
print(ran.max())
print(np.sum(ran))
print(ran.sum())
print(np.mean(ran))
print(ran.mean())
print(np.median(ran))
print(ran.median())

27
27
459
459
5535
5535
221.4
221.4
201.0


AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [19]:
# logarithms and exponentials
np.log(1)

0.0

In [20]:
np.log([6,7,20])

array([1.79175947, 1.94591015, 2.99573227])

In [21]:
np.log(man)

C:\Users\ruthu\AppData\Local\Temp\ipykernel_24912\3471324498.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(man)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383]])

In [22]:
np.exp(1)

2.718281828459045

In [23]:
np.exp(2)

7.38905609893065

In [24]:
np.exp(ran)

array([[2.19364928e+199, 4.79781333e+051, 6.51611463e+126,
        1.27089863e+062, 2.23524660e+037],
       [5.32048241e+011, 4.81479366e+127, 4.10848636e+111,
        3.12631016e+178, 3.31740010e+039],
       [2.01566233e+077, 1.96422332e+087, 1.02981983e+066,
        1.22040329e+039, 1.79113982e+084],
       [3.11528461e+102, 2.19364928e+199, 1.81764939e+117,
        3.32914098e+115, 1.20686052e+082],
       [8.37424995e+145, 3.18559318e+016, 6.16595783e+070,
        7.92424244e+089, 5.35820935e+163]])

In [26]:
 # the difference b/w normal functions and numpy functions
def greater(a,b):
    if a>b:
        return a
    else:
        return b
    
greater(5,10),greater(15,9),greater([90,34,56],[86,45,15]) # [90,45,56]

(10, 15, [90, 34, 56])

In [27]:
g=np.vectorize(greater)
g([90,34,56],[86,45,15])

array([90, 45, 56])

#### pandas
- pandas means PanelData which represents the data in table format
- it contains rows and columns
- it has 2 data structures
    1. Series
        - 1 dimensional data structure
        - sequential data points arranged either side by side or line by line
        - pd.Series(data)
    2. Data Frame
        - 2d data
        - contains rows and columns
        - pd.DataFrame(data)

In [28]:
pd.Series([4,5,6,7,10,90])

0     4
1     5
2     6
3     7
4    10
5    90
dtype: int64

In [30]:
pd.Series(np.random.randint(100,303,15),index=[v for v in range(1,16)])

1     244
2     282
3     245
4     144
5     259
6     154
7     202
8     233
9     246
10    219
11    184
12    285
13    140
14    200
15    230
dtype: int32

In [32]:
# data frame
df=pd.DataFrame({'int':(1,2,3),'float':[4.2,5.0,6.3],
                'str':['a','b','c']},index=['R1','R2','R3'])
df

int  float str
R1    1    4.2   a
R2    2    5.0   b
R3    3    6.3   c

In [33]:
# working with .csv file
data=pd.read_csv("clg.csv")
data

Student    Faculty  ML  DS  CC  Web  Java  Python     C  DBMS  OS  \
0   Pravallika      Madhu  87  88  91   92    90    96.0    85    95  95   
1        Bhanu       Neil  94  88  92   90    92    94.0    94    93  95   
2    Chandrika   Abhishek  99  87  89   92    94    87.0  9488    91  98   
3        Divya   Chandana  88  89  97   92    87   930.0    87    89  89   
4       Elisha     Harsha  95  85  91   95    85    97.0    91    89  86   
5      Thanuja    Lalitha  87  92  96   91    90    98.0    87    91  96   
6        Divya   Maalathi  93  87  91   90    99    94.0    91    90  87   
7      Fathima    Nithesh  98  89  90   91    95    90.0    98    99  85   
8        Kavya      Ashok  96  94  91   97    92     NaN    85    90  93   
9      Neelima     Bhavya  91  89  97   86    87    86.0    95    97  99   
10       Navya     Dinesh  96  96  87   90    93    97.0   100    91  88   
11      Sindhu     Yamini  97  90  92   91    85    85.0    98   100  93   
12     Mallika  Geethika'  95  94  95   92   100    89.0    88    89  85   
13     Madhavi          S  87  97  93   88    91    97.0    97    99  87   
14      Naresh          x  97  99  97   99    91    98.0    92    94  90   

    Algorithms     CN  
0         89.0    NaN  
1         96.0    NaN  
2          NaN    NaN  
3          NaN    NaN  
4        100.0  100.0  
5         87.0    NaN  
6         93.0   98.0  
7         95.0    NaN  
8        100.0    NaN  
9         92.0    NaN  
10        93.0   89.0  
11        88.0  100.0  
12        91.0   97.0  
13        98.0   86.0  
14        90.0   93.0

In [34]:
# generates first five samples
data.head()

Student   Faculty  ML  DS  CC  Web  Java  Python     C  DBMS  OS  \
0  Pravallika     Madhu  87  88  91   92    90    96.0    85    95  95   
1       Bhanu      Neil  94  88  92   90    92    94.0    94    93  95   
2   Chandrika  Abhishek  99  87  89   92    94    87.0  9488    91  98   
3       Divya  Chandana  88  89  97   92    87   930.0    87    89  89   
4      Elisha    Harsha  95  85  91   95    85    97.0    91    89  86   

   Algorithms     CN  
0        89.0    NaN  
1        96.0    NaN  
2         NaN    NaN  
3         NaN    NaN  
4       100.0  100.0

In [36]:
data.head(3)#first n samples

Student   Faculty  ML  DS  CC  Web  Java  Python     C  DBMS  OS  \
0  Pravallika     Madhu  87  88  91   92    90    96.0    85    95  95   
1       Bhanu      Neil  94  88  92   90    92    94.0    94    93  95   
2   Chandrika  Abhishek  99  87  89   92    94    87.0  9488    91  98   

   Algorithms  CN  
0        89.0 NaN  
1        96.0 NaN  
2         NaN NaN

In [37]:
data.tail() # last 5 samples

Student    Faculty  ML  DS  CC  Web  Java  Python    C  DBMS  OS  \
10    Navya     Dinesh  96  96  87   90    93    97.0  100    91  88   
11   Sindhu     Yamini  97  90  92   91    85    85.0   98   100  93   
12  Mallika  Geethika'  95  94  95   92   100    89.0   88    89  85   
13  Madhavi          S  87  97  93   88    91    97.0   97    99  87   
14   Naresh          x  97  99  97   99    91    98.0   92    94  90   

    Algorithms     CN  
10        93.0   89.0  
11        88.0  100.0  
12        91.0   97.0  
13        98.0   86.0  
14        90.0   93.0

In [38]:
data.tail(3)#last 3 samples

Student    Faculty  ML  DS  CC  Web  Java  Python   C  DBMS  OS  \
12  Mallika  Geethika'  95  94  95   92   100    89.0  88    89  85   
13  Madhavi          S  87  97  93   88    91    97.0  97    99  87   
14   Naresh          x  97  99  97   99    91    98.0  92    94  90   

    Algorithms    CN  
12        91.0  97.0  
13        98.0  86.0  
14        90.0  93.0

In [40]:
data.sample()# any random sample

Student Faculty  ML  DS  CC  Web  Java  Python   C  DBMS  OS  \
0  Pravallika   Madhu  87  88  91   92    90    96.0  85    95  95   

   Algorithms  CN  
0        89.0 NaN

In [41]:
# generate n random samples
data.sample(5)

Student    Faculty  ML  DS  CC  Web  Java  Python   C  DBMS  OS  \
7      Fathima    Nithesh  98  89  90   91    95    90.0  98    99  85   
8        Kavya      Ashok  96  94  91   97    92     NaN  85    90  93   
0   Pravallika      Madhu  87  88  91   92    90    96.0  85    95  95   
12     Mallika  Geethika'  95  94  95   92   100    89.0  88    89  85   
4       Elisha     Harsha  95  85  91   95    85    97.0  91    89  86   

    Algorithms     CN  
7         95.0    NaN  
8        100.0    NaN  
0         89.0    NaN  
12        91.0   97.0  
4        100.0  100.0